config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'mypage', to: 'users#show'

  get 'account', to: 'users#account'

  resources :posts

  get 'search', to: 'posts#index', as: 'search'

  get 'users/edit_password', to: 'users#edit_password', as: 'edit_password'
  patch 'users/update_password', to: 'users#update_password', as: 'update_password'

  resources :favorites, only: [:create, :destroy, :index]

  resources :users, only: [:create, :show] do
    resources :posts, only: [:index] 
    get 'favorites', to: 'favorites#index' 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  # ユーザーが同じ投稿を複数回お気に入りにできないようにする
   validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user  # FK
  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :user
  has_one_attached :photo  # Active Storageを利用して写真を添付

  # 焙煎度のenum定義
  enum roast_level: {
    raw_beans: 0,
    light_roast: 1,
    cinnamon_roast: 2,
    medium_roast: 3,
    high_roast: 4,
    city_roast: 5,
    fullcity_roast: 6,
    french_roast: 7,
    italian_roast: 8
  }

  validates :store_name, presence: true
  validates :beans_name, presence: true
  validates :roast_level, inclusion: { in: roast_levels.keys }

  def self.roast_level_names
    {
      raw_beans: '生豆',
      light_roast: 'ライトロースト',
      cinnamon_roast: 'シナモンロースト',
      medium_roast: 'ミディアムロースト',
      high_roast: 'ハイロースト',
      city_roast: 'シティロースト',
      fullcity_roast: 'フルシティロースト',
      french_roast: 'フレンチロースト',
      italian_roast: 'イタリアンロースト'
    }
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password  # Rails標準の認証機能

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  validates :user_name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, length: { minimum: 4 }, if: -> { new_record? || !password.nil? }
  validates :password_confirmation, presence: true, if: -> { new_record? || !password.nil? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def require_login
    unless logged_in?
      flash[:error] = "ログインが必要です"
      redirect_to login_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_login

  def index
    # 現在のユーザーがお気に入りに登録した投稿を取得
    @favorite_posts = current_user.favorite_posts
  end

  def create
  post = Post.find(params[:post_id])

    # 自分自身の投稿はお気に入り登録できないようにする
    if post.user_id == current_user.id
      redirect_to post_path(post), alert: '自分の投稿はお気に入り登録できません'
    else
      current_user.favorite_posts << post
      redirect_to post_path(post), notice: 'お気に入りに登録しました'
    end
  end

  def destroy
    favorite = current_user.favorites.find(params[:id])  # params[:id] でFavoriteを取得
    post = favorite.post  # 関連するPostを取得
    favorite.destroy
    redirect_to post_path(post), notice: 'お気に入りを解除しました'
  end
end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    if params[:q].present?
      search_query = params[:q].strip
      roast_level = find_roast_level_by_query(search_query)  # 検索キーワードに基づいて焙煎度を見つける

      query_conditions = [
        "store_name LIKE :query",
        "beans_name LIKE :query",
        "coffee_growing_regions LIKE :query",
        "memo LIKE :query"
      ]

      # roast_level が見つかった場合に条件に追加
      if roast_level
        query_conditions << "roast_level = :roast_level"
      end

      @posts = Post.where(
        query_conditions.join(" OR "),
        query: "%#{search_query}%",
        roast_level: roast_level
      )
    else
      @posts = Post.all
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to mypage_path, notice: '投稿が成功しました。'
    else
      flash.now[:alert] = '投稿に失敗しました。'
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])  # params[:id]で指定された投稿を取得
  end

  def edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: '投稿が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "投稿を削除しました。"
  end

  private

  def find_roast_level_by_query(query)
    Post.roast_level_names.each do |key, name|
      return Post.roast_levels[key] if name.include?(query) || key.to_s.include?(query.downcase)
    end
    nil
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def correct_user
    if @post.nil? || current_user != @post.user
      flash[:alert] = "この操作を実行する権限がありません。"
      redirect_to(root_path)
    end
  end

  def post_params
    params.require(:post).permit(:store_name, :beans_name, :roast_level, :coffee_growing_regions, :photo, :memo)
  end

  def require_login
    unless logged_in?
      flash[:error] = "ログインが必要です"
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])  # Rails標準のauthenticateメソッド
      session[:user_id] = user.id  # セッションにユーザーIDを保存
      redirect_to mypage_path, notice: "ログインに成功しました。"
    else
      flash.now[:alert] = "メールアドレスまたはパスワードが間違っています。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil  # セッションをクリアしてログアウト
    redirect_to root_path, status: :see_other
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :set_url_options

  def index
    @posts = Post.limit(6).order(created_at: :desc)
  end

  private

  def set_url_options
    ActiveStorage::Current.url_options = { host: request.base_url }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully signed up!"
    else
      render 'new'
    end
  end

  def show
    @user = current_user  # 現在のログインユーザー
    @posts = @user.posts.limit(6).order(created_at: :desc)  # 自身の投稿
    @favorites = @user.favorite_posts.limit(6).order(created_at: :desc)  # お気に入り投稿
  end

  def account
    @user = current_user  # 現在のログインユーザーを取得
  end

    # パスワード編集ページの表示
    def edit_password
      @user = current_user
    end
  
    # パスワードの更新処理
    def update_password
      @user = current_user
      if @user.update(user_params)
        redirect_to account_path, notice: 'パスワードが更新されました。'
      else
        render 'edit_password'
      end
    end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

  def require_login
    unless current_user
      flash[:error] = "ログインが必要です"
      redirect_to login_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="container">
  <h1>お気に入り投稿一覧</h1>

  <div class="post-container">
    <% if @favorite_posts.any? %>
      <% @favorite_posts.each do |post| %>
        <div class="post">
          <% if post.photo.present? %>
            <%= image_tag(post.photo, alt: '投稿の画像', class: 'posts-image') %>
          <% else %>
            <%= image_tag('no_image.jpg', alt: '投稿の画像', class: 'posts-image') %>
          <% end %>
          <h2><%= link_to post.store_name, post_path(post) %></h2>
          <p><%= truncate(post.memo, length: 100) %></p>
        </div>
      <% end %>
    <% else %>
      <p>お気に入りに登録された投稿はありません。</p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>コーヒー管理アプリ</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="/assets/application.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <%= javascript_include_tag 'application', type: 'module' %>
  <meta name="turbo-cache-control" content="no-cache">
</head>

<body>
  <header>
    <%= render 'shared/header' %>
  </header>
  
  <div style="background-image: url('<%= asset_path('coffee_beans.jpg') %>'); background-size: cover; text-align: center; padding: 100px 0;">
  </div>

  <% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
  
  <%= yield %>
</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>投稿編集</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> が発生しました:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :store_name, '店舗名' %><br>
    <%= form.text_field :store_name %>
  </div>

  <div class="field">
    <%= form.label :beans_name, 'コーヒー豆' %><br>
    <%= form.text_field :beans_name %>
  </div>

  <div class="field">
    <%= form.label :roast_level, '焙煎度' %><br>
    <%= form.select :roast_level, options_for_select(Post.roast_levels.map { |key, value| [Post.roast_level_names[key.to_sym], key] }, @post.roast_level), { include_blank: '選択してください' } %>
  </div>

  <div class="field">
    <%= form.label :coffee_growing_regions, '生産地' %><br>
    <%= form.text_field :coffee_growing_regions %>
  </div>

  <div class="field">
    <%= form.label :photo, '写真をアップロード' %><br>
    <% if @post.photo.attached? %>
      <%= image_tag @post.photo.variant(resize_to_limit: [300, 300]).processed %><br>
    <% end %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.label :memo, 'メモ' %><br>
    <%= form.text_area :memo %>
  </div>

  <div class="actions">
    <%= form.submit '更新する' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <h1><%= params[:q].present? ? "「#{params[:q]}」の検索結果" : "最新投稿" %></h1>

  <div class="post-container">
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div class="post">
          <% if post.present? && post.photo.present? %>
            <%= image_tag(post.photo, alt: '投稿の画像', class: 'posts-image') %>
          <% else %>
            <%= image_tag('no_image.jpg', alt: '投稿の画像', class: 'posts-image') %>
          <% end %>
          <h2><%= link_to post.store_name, post_path(post) %></h2>
          <p>コーヒー豆: <%= post.beans_name %></p>
          <p>焙煎度: <%= Post.roast_level_names[post.roast_level.to_sym] %></p>
          <p>生産地: <%= post.coffee_growing_regions %></p>
        </div>
      <% end %>
    <% else %>
      <p>検索に一致する投稿がありません。</p>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :store_name, '店舗名' %><br>
    <%= form.text_field :store_name %>
  </div>

  <div class="field">
    <%= form.label :beans_name, 'コーヒー豆' %><br>
    <%= form.text_field :beans_name %>
  </div>

  <div class="field">
    <%= form.label :roast_level, '焙煎度' %><br>
    <%= form.select :roast_level, options_for_select(Post.roast_level_names.map { |key, value| [value, key] }), include_blank: '選択してください' %>
  </div>

  <div class="field">
    <%= form.label :coffee_growing_regions, '生産地' %><br>
    <%= form.text_field :coffee_growing_regions %>
  </div>

  <div class="field">
    <%= form.label :photo, '写真をアップロード' %><br>
    <%= form.file_field :photo %>  <!-- ここでファイルをアップロード -->
  </div>

  <div class="field">
    <%= form.label :memo, 'メモ' %><br>
    <%= form.text_area :memo %>
  </div>

  <div class="actions">
    <%= form.submit '投稿する' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<body>
  <div class="container">
      <div class="post">
        <div class="post-container">
          <div class="post-image">
            <% if @post.present? && @post.photo.present? %>
              <%= image_tag(@post.photo, alt: '投稿の画像', class: 'posts-image') %>
            <% else %>
              <%= image_tag('no_image.jpg', alt: '投稿の画像', class: 'posts-image') %>
            <% end %>
          </div>
          <div class="post-content">
            <h2><%= @post.store_name %></h2>
            <p><%= @post.beans_name %></p>
            <% roast_levels = {
              'raw_beans' => '生豆',
              'light_roast' => 'ライトロースト',
              'cinnamon_roast' => 'シナモンロースト',
              'medium_roast' => 'ミディアムロースト',
              'high_roast' => 'ハイロースト',
              'city_roast' => 'シティロースト',
              'fullcity_roast' => 'フルシティロースト',
              'french_roast' => 'フレンチロースト',
              'italian_roast' => 'イタリアンロースト'
            } %>
            <p>焙煎度: <%= roast_levels[@post.roast_level] || '不明な焙煎度' %></p>
            <p>生産地: <%= @post.coffee_growing_regions %></p>
            <p>メモ: <%= @post.memo %></p>

            <% if logged_in? && current_user == @post.user %>
              <div class="button-group">
                <%= link_to '編集', edit_post_path(@post), class: "btn-primary btn-small" %>
                
                <%= form_with(url: post_path(@post), method: :delete, local: true, class: "inline-form") do %>
                  <%= submit_tag '削除', class: "btn-primary btn-small", data: { confirm: "本当に削除しますか？" } %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</body>



app/views/shared/_header.html.erb
<div class="navbar">
  <div class="navbar-brand">
    <%= link_to 'コーヒー管理アプリ', root_path %>
  </div>

  <div class="navbar-center">
    <%= form_with(url: search_path, method: :get, local: true, class: "search-form") do |form| %>
      <%= form.text_field :q, placeholder: "検索ワードを入力", class: "search-input" %>
      <%= form.submit "検索", class: "search-button" %>
    <% end %>
  </div>

  <nav>
    <ul>
      <li><%= link_to 'ホーム', root_path %></li>
      <% if logged_in? %>
        <li><%= link_to 'マイページ', mypage_path %></li>
        <li><%= link_to 'アカウント', account_path %></li>
        <li><%= link_to '新規投稿', new_post_path %></li>

        <li>
          <%= form_with(url: logout_path, method: :delete, local: true) do %>
            <%= submit_tag 'ログアウト', class: 'logout-button' %>
          <% end %>
        </li>
        
      <% else %>
        <li><%= link_to '新規登録', signup_path %></li>
        <li><%= link_to 'ログイン', login_path %></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/tops/index.html.erb
<div class="container">
  <h1>最新投稿</h1>

  <div class="post-container">
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div class="post">
          <% if post.present? && post.photo.present? %>
            <%= image_tag(post.photo, alt: '投稿の画像', class: 'posts-image') %>
          <% else %>
            <%= image_tag('no_image.jpg', alt: '投稿の画像', class: 'posts-image') %>
          <% end %>
          <h2><%= link_to post.store_name, post_path(post) %></h2>
          <p><%= post.beans_name %></p>
          <p><%= Post.roast_level_names[post.roast_level.to_sym] %></p>

          <!-- ログインしている場合のみお気に入りボタンを表示 -->
          <% if logged_in? && post.user_id != current_user.id %>
            <span class="favorite" data-post-id="<%= post.id %>">
              <% if favorite = current_user.favorites.find_by(post_id: post.id) %>
                <!-- お気に入り解除フォーム -->
                <%= form_with url: favorite_path(favorite), method: :delete, local: true do %>
                  <button type="submit" class="star-button">
                    <i class="fas fa-star filled"></i> <!-- 塗りつぶされた星 -->
                  </button>
                <% end %>
              <% else %>
                <!-- お気に入り登録フォーム -->
                <%= form_with url: favorites_path(post_id: post.id), method: :post, local: true do %>
                  <button type="submit" class="star-button">
                    <i class="far fa-star"></i> <!-- 空の星 -->
                  </button>
                <% end %>
              <% end %>
            </span>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p>表示できる投稿がありません。</p>
    <% end %>
  </div>

  <% if Post.count >= 6 %>
    <div class="center-button">
      <%= link_to '投稿一覧を見る', posts_path, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/account.html.erb
<!-- app/views/users/account.html.erb -->
<h1>アカウント情報</h1>

<p>メールアドレス: <%= @user.email %></p>

<p>パスワード: ******</p> <!-- パスワードは通常表示しない -->

<%= link_to 'パスワードを変更する', edit_password_path %> <!-- 修正されたパスワード変更リンク -->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit_password.html.erb
<!-- app/views/users/edit_password.html.erb -->
<h1>パスワードを変更する</h1>

<%= form_with(model: @user, url: update_password_path, method: :patch) do |f| %>
  <div>
    <%= f.label :パスワード %><br>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :パスワード（確認） %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit 'パスワードを更新する' %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>新規登録画面</h1>

<%= form_with(model: @user, url: signup_path, local: true) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ユーザーネーム %><br>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :メールアドレス %><br>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :パスワード %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :パスワード（確認） %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "新規登録" %>
  </div>

<% end %>

app/views/users/show.html.erb
<div class="container">
  <h1>マイページ</h1>

  <h2>自身の投稿</h2>
  <div class="post-container">
    <% if @posts.any? %>
      <% @posts.take(3).each do |post| %>  <!-- 最初の3件のみを取得 -->
        <div class="post">
          <% if post.present? && post.photo.present? %>
            <%= image_tag(post.photo, alt: '投稿の画像', class: 'posts-image') %>
          <% else %>
            <%= image_tag('no_image.jpg', alt: '投稿の画像', class: 'posts-image') %>
          <% end %>
          <h2><%= link_to post.store_name, post_path(post) %></h2>
          <p><%= Post.roast_level_names[post.roast_level.to_sym] %></p>
        </div>
      <% end %>
    <% else %>
      <p>表示できる投稿がありません。</p>
    <% end %>
  </div>

  <!-- ボタンを中央に配置 -->
  <% if @posts.count >= 3 %>
    <div class="center-button">
      <%= link_to 'More', user_posts_path(@user), class: 'btn btn-primary' %>
    </div>
  <% end %>

  <h2>お気に入り</h2>
  <div class="post-container">
    <% @favorites.take(3).each do |post| %>  <!-- 最初の3件のみを取得 -->
      <div class="post">
      <% if post.present? && post.photo.present? %>
      <%= image_tag(post.photo, alt: '投稿の画像', class: 'posts-image') %>
    <% else %>
      <%= image_tag('no_image.jpg', alt: '投稿の画像', class: 'posts-image') %>
    <% end %>
    <h2><%= link_to post.store_name, post_path(post) %></h2>
    <p><%= Post.roast_level_names[post.roast_level.to_sym] %></p>
      </div>
    <% end %>
  </div>

  <!-- お気に入りの「More」ボタンも中央に配置 -->
  <% if @favorites.count >= 3 %>
    <div class="center-button">
      <%= link_to 'More', user_favorites_path(@user), class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
